version: 0.2

env:
  variables:
    NODE_ENV: "prod"
    DB_DIALECT: "mysql"

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      ### Docker Specific Environment Variables
      # - export DB_USERNAME = $MYSQL_USER
      # - export DB_PASSWORD = $MYSQL_PASSWORD
      # - export DB_DATABASE = $MYSQL_DATABASE
      ### Hardcoded Environment Variables
      # - export DB_USERNAME=lenaadmin
      # - export DB_PASSWORD=lenaadmin
      # - export DB_DATABASE=consumer
      # - export DB_HOST=consumer.c95v7ebbwqka.us-west-1.rds.amazonaws.com
      ### aws EC2 Specific Environment Variables
      - export DB_USERNAME=$(aws ssm get-parameters --region us-west-1 --names DB_USERNAME --query Parameters[0].Value | cut -d'"' -f2)
      - export DB_PASSWORD=$(aws ssm get-parameters --region us-west-1 --names DB_PASSWORD --query Parameters[0].Value | cut -d'"' -f2)
      - export DB_HOST=$(aws ssm get-parameters --region us-west-1 --names DB_HOST --query Parameters[0].Value | cut -d'"' -f2)
      - export DB_DATABASE=$(aws ssm get-parameters --region us-west-1 --names DB_DATABASE --query Parameters[0].Value | cut -d'"' -f2)
      - echo $NODE_ENV $DB_USERNAME $DB_PASSWORD $DB_HOST $DB_DIALECT $DB_DATABASE
      ### date and utility versioning for reference
      - echo Build started on `date`
      - npm --version
      - node --version
      - aws --version
      ### npm test
      - npm test
      - yum install -y docker && service docker start && docker-compose up -d .

# artifacts:
  # type: s3
  # location: lena-consumer
