version: 0.2

env:
  variables:
    DB_USERNAME: "lenaadmin"
    DB_PASSWORD: "aaaaaaaaa"
    DB_DIALECT: "mysql"
    NODE_ENV: "prod"

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
      - npm test
