version: 0.2

env:
  variables:
    NODE_ENV: "prod"

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - echo $NODE_ENV $DB_USERNAME $DB_PASSWORD $DB_HOST $DB_DIALECT
      - npm install
  pre_build:
    commands:
      - export DB_USERNAME=$(aws ssm get-parameters --region us-west-1 --names DB_USERNAME --query Parameters[0].Value)
      - export DB_PASSWORD=$(aws ssm get-parameters --region us-west-1 --names DB_PASSWORD --query Parameters[0].Value)
      - export DB_DIALECT=$(aws ssm get-parameters --region us-west-1 --names DB_DIALECT --query Parameters[0].Value)
      - export DB_HOST=$(aws ssm get-parameters --region us-west-1 --names DB_HOST --query Parameters[0].Value)
      - export DB_DATABASE=$(aws ssm get-parameters --region us-west-1 --names DB_DATABASE --query Parameters[0].Value)
      - echo $NODE_ENV $DB_USERNAME $DB_PASSWORD $DB_HOST $DB_DIALECT $DB_DATABASE
      - echo Build started on `date`
      - npm test

# artifacts:
  # type: s3
  # location: lena-consumer
