version: '3'
services:
  node:
    build:
      context: .
      dockerfile: dockerfile/node
    image: nsaboo/node
    volumes:
      - .:/code
      - logvolume01:/var/log
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: dockerfile/mysql
    image: nsaboo/mysql
  python:
    build:
      context: .
      dockerfile: dockerfile/python
    image: nsaboo/python
volumes:
  logvolume01: {}
