version: '3'
services:
  node:
    build:
      context: .
      dockerfile: build/node/Dockerfile
    image: nsaboo/node
    volumes:
      - .:/code
      - logvolume01:/var/log
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    build:
      context: build/mysql/
      dockerfile: Dockerfile
    image: nsaboo/mysql
  python:
    build:
      context: build/python/
      dockerfile: Dockerfile
    image: nsaboo/python
volumes:
  logvolume01: {}
