version: '3.3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    # depends_on:
      # - elasticsearch1
    ports:
      - 5601:5601
    networks:
      - back-tier
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - 9200:9200
    networks:
      - back-tier
    environment:
      - cluster.name=lena-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    networks:
      - back-tier
    environment:
      - cluster.name=lena-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data

networks:
  back-tier:
   driver: bridge
  # front-tier:

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
