version: '3.3'
services:
  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-tier
    environment:
      - cluster.name=lena-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    networks:
      - elk-tier
    environment:
      - cluster.name=lena-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - 5601:5601
    networks:
      - elk-tier
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash:
    build:
      context: build/logstash/
      dockerfile: Dockerfile
    # image: nsaboo/logstash
    ports:
      - 5000:5000
    environment:
      - xpack.monitoring.enabled=false
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-tier
    volumes:
      - logstash-data:/usr/share/logstash/data

networks:
  elk-tier:
   driver: bridge

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  logstash-data:
    driver: local
  lena-data:
    driver: local
