version: '3.3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.instance == lena-elasticsearch
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - lena-tier
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=lena-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
#    deploy:
#      replicas: 1
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.instance == lena-elasticsearch
#      update_config:
#        parallelism: 1
#        delay: 10s
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#    networks:
#      - lena-tier
#    volumes:
#      - esdata2:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=lena-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536
#      memlock:
#        soft: -1
#        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
#          - node.role == worker
#          - node.labels.instance == lena-kibana
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - lena-tier
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  logstash:
    image: nsaboo/logstash
    #image: docker.elastic.co/logstash/logstash:5.6.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.instance == lena-logstash
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - lena-tier
    volumes:
      - logstash-data:/usr/share/logstash/data
    ports:
      - 5000:5000
    environment:
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
  node:
    build:
      context: .
      dockerfile: dockerfile/node
    image: nsaboo/node
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.instance == lena-web
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - lena-tier
    volumes:
      - lenalog:/var/log
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prod
      - DB_USERNAME=lenaadmin
      - DB_PASSWORD=lenaadmin
      - DB_DATABASE=consumer
      - DB_HOST=consumer.c95v7ebbwqka.us-west-1.rds.amazonaws.com
      - DB_DIALECT=mysql

networks:
  lena-tier:
    driver: overlay

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  logstash-data:
    driver: local
  lena-data:
    driver: local
  lenalog:
    driver: local
