-- MySQL Script generated by MySQL Workbench
-- Sat Oct 21 15:26:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema consumer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consumer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consumer` DEFAULT CHARACTER SET utf8 ;
USE `consumer` ;

-- -----------------------------------------------------
-- Table `consumer`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `mobile` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `firstname` VARCHAR(64) NOT NULL COMMENT '		',
  `lastname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`zipcodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`zipcodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zipcode` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `city` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `zipcode_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `addresses_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addresses_zipcode_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`zipcodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addresses_city_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `card_type` VARCHAR(64) NOT NULL,
  `card_number` INT NOT NULL,
  `card_expiry` VARCHAR(8) NOT NULL,
  `card_cvv` VARCHAR(8) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `payments_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `carts_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carts_product_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumer`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `review` VARCHAR(264) NOT NULL,
  `rating` TINYINT(5) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `reviews_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviews_product_id`
    FOREIGN KEY (`id`)
    REFERENCES `consumer`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
